name: my-cml
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: "Train my model"
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py

          # Write your CML report
          echo "# Models metrics" >> report.md
          cat results.txt >> report.md
          
          # Image
          cml-publish image.png --md >> report.mdr
          
          cml-send-comment report.md
